sitewomen/sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include  # импорт include

from sitewomen import settings
from women.views import page_not_found  # импорт page_not_found(после его представления!)
# + папку sitewomen сделали sourse root(рабочий каталог) из-за конфликта в import

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),  # Спец. Функция include позволяет подключить все маршруты автоматически. Если
    # на месте '' прописать свой индекс и еще в файле women/urls.py - то он будет добавляться к адресу автоматически
    path('users/', include('users.urls', namespace="users")),  # путь + связка с приложением users + namespace
    path("__debug__/", include("debug_toolbar.urls")),  # путь для django toolbar
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Связка маршрута MEDIA_URL с
    # общим каталогом sitewomen/media (MEDIA_ROOT) в режиме Debug для корректной работы сервера при обращении в этом
    # режиме и в режиме работы.

handler404 = page_not_found  # обработчик handler404 + ссылка на нашу ф-ию для вывода нашего сообщения при ошибке

admin.site.site_header = "Панель администрирования"  # наш заголовок админки
admin.site.index_title = "Известные женщины мира"  # заголовок ниже уровнем

sitewomen/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy  # импорт функций path
from . import views  # импорт views из текущего модуля

app_name = "users"  # обязательное определение переменной с названием users

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),  # маршрут для авторизации с помощью class LoginUser
    path('logout/', views.logout_user, name='logout'),  # маршрут для выхода с помощью ф-ии logout_user.

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),  # Пользовательский класс для
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),  # смены пароля (template_name=переопределение шаблона со станд-го на пользов-ий)

    path('password-reset/',  # маршруты для стандартных классов сброса пароля
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",  # пользовательский шаблон
             email_template_name="users/password_reset_email.html",  # шаблон, формирующий текст сообщения на email
             success_url=reverse_lazy("users:password_reset_done")), name='password_reset'),  # перенаправление
    path('password-reset/done/',  # сообщение о сбросе пароля
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',  # маршруты для стан-ых классов восстановления пароля
         PasswordResetConfirmView.as_view(  # спец токен (из доку) --> на почту для восстановления пароля
             template_name="users/password_reset_confirm.html",  # пользовательский шаблон
             success_url=reverse_lazy("users:password_reset_complete")),  name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),  # сообщение об успешности восстановления и ссылка на вход



    path('register/', views.RegisterUser.as_view(), name='register'),  # маршрут для класса регистрации пользователя
    path('profile/', views.ProfileUser.as_view(), name='profile'),  # маршрут для класса профиля пользователя
]

sitewomen/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):  # Модель User наследие от стандартного AbstractUser + пользовательские поля
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name="Фотография")
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения")

sitewomen/users/forms.py
from datetime import date

from django import forms  # импортируем из django
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):  # класс для авторизации (форма не связана с моделью)
    username = forms.CharField(label="Логин",  # стиль оформления через widget + attrs{класс и стили}
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Пароль",  # поле для пароля.
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:  # Класс, указывающий явную связь с моделью + отображаемые поля(класс как дополнение атрибутам выше)
        model = get_user_model()  # get_user_model возвращает текущую модель пользователя(если в будущем модель
        # пользователя меняется, то get_user_model вернет указанную, вместо стандартной - good practice!)
        fields = ['username', 'password']  # поля для отображения


class RegisterUserForm(UserCreationForm):  # Класс форма для рег-ии пользователя(связана с моделью) тип UserCreationForm
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Повтор пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    # Обязательные атрибуты (поля для заполнения)

    class Meta:  # Вложенный класс (так как основной класс связан с моделью)
        model = get_user_model()  # Возвращает текущую модель пользователя
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']  # поля отображаемые в форме
        labels = {  # метки для полей
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {  # через атрибут widgets назначить стили для указанных полей
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):  # Валидатор проверки на уникальность email-адреса
        email = self.cleaned_data['email']  # данные с ключом по email
        if get_user_model().objects.filter(email=email).exists():  # Из модели пользователя отбирает польз-я по email,
            # если такой найден, тогда отрабатывает генерация исключения
            raise forms.ValidationError("Такой E-mail уже существует!")  # исключение, если проверка не прошла
        return email


class ProfileUserForm(forms.ModelForm):  # Форма для профиля пользователя(отображаемые поля), связан с моделью
    username = forms.CharField(disabled=True, label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label="E-mail", widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = date.today().year  # Стандартный модуль для получения текущего года
    date_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year-100, this_year-5))))  # Спец
    #  widget для удобного заполнения поля даты + диапазон возраста от 5-100 лет

    class Meta:
        model = get_user_model()  # Стараться использовать get_user_model() вместо обычного обращения user!
        fields = ['photo', 'username', 'email', 'date_birth', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {  # стили полей
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):  # Форма для смены пароля(наследие от стандартного PasswordChangeForm)
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",  # + {'class': 'form-input'} - стиль полей
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

sitewomen/users/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

import settings
from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):  # класс типа LoginView для авторизации(наследуется от LoginView)
    form_class = LoginUserForm  # атрибут формы класса(наследуется от стандартной AuthenticationForm)
    template_name = 'users/login.html'  # название и путь к шаблону
    extra_context = {'title': 'Авторизация'}  # передача в шаблон заголовка

    # def get_success_url(self):  # спец метод переопределяющий переход на указанную стран-у, после успешной авторизации
    #     return reverse_lazy('home')  # явно указать возврат и маршрут страницы(в данном случае - главная)


def logout_user(request):  # ф-я для выхода авторизованного пользователя
    logout(request)  # спец ф-я logout для выхода из системы
    return HttpResponseRedirect(reverse("home"))  # перенаправление по указанному маршруту(главная страница)


class RegisterUser(CreateView):  # Класс аналог def register. Проверяет корректность заполненности формы и сохр-ет в БД.
    form_class = RegisterUserForm  # атрибут используемой формы
    template_name = 'users/register.html'  # используемый шаблон
    extra_context = {'title': "Регистрация"}  # Заголовок с текстом
    success_url = reverse_lazy('users:login')  # маршрут для перенаправления пользователя после успешной регистрации.


class ProfileUser(LoginRequiredMixin, UpdateView):  # Класс пред-я для профиля пользователя(Mixin - запрет просмотра
    model = get_user_model()          # профиля для не авторизованных пользователей, Update - изменение текущих записей.
    form_class = ProfileUserForm  # ссылка на форму ProfileUserForm
    template_name = 'users/profile.html'  # шаблон
    extra_context = {'title': "Профиль пользователя",  # Заголовок + текст
                     'default_image': settings.DEFAULT_USER_IMAGE  # Параметр для отображения стандартной аватарки
                     }

    def get_success_url(self):  # метод для перенаправления на указанный адрес, после изменения записей
        return reverse_lazy('users:profile')  # возврат на текущую страницу

    def get_object(self, queryset=None):  # Метод, возвращающий запись, которая редактируется
        return self.request.user  # обращение к текущему пользователю


class UserPasswordChange(PasswordChangeView):  # Класс предс-я для смены пароля (наследие от стандартного класса -->
    form_class = UserPasswordChangeForm  # Ссылка на собственную форму.                         --> PasswordChangeView)
    success_url = reverse_lazy("users:password_change_done")  # перенаправление по указанному адресу
    template_name = "users/password_change_form.html"  # путь к шаблону

sitewomen/users/templates/users/login.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->

{% block content %}  <!-- Переопределение блока content -->
<h1>Авторизация</h1>

<form method="post">  <!-- Форма для передачи данных методом post -->
    {% csrf_token %}  <!-- Обязательный атрибут csrf -->
    <input type="hidden" name="next" value="{{ next }}" />  <!--Переход на следущ указан страницу, после авторизации -->
    <div class="form-error">{{ form.non_field_errors }}</div>  <!-- Отображение ошибок в заполнении полей формы-->
    {% for f in form %} <!-- Цикл для перебора и отображения полей формы-->
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>  <!-- Вывод текущего поля-->
    <div class="form_error">{{ f.errors }}</div>  <!--Отображение ошибок, связанных с полями-->
    {% endfor %}
    <p><button type="submit">Войти</button></p>
</form>

{% endblock %}

sitewomen/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

sitewomen/users/templates/users/password_change_form.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->

{% block content %}  <!-- Переопределение блока content -->
<h1>Изменение пароля</h1>

<form method="post">  <!-- Форма для передачи данных методом post -->
    {% csrf_token %}  <!-- Обязательный атрибут csrf -->
    <div class="form-error">{{ form.non_field_errors }}</div>  <!-- Отображение ошибок в заполнении полей формы-->
    {% for f in form %} <!-- Цикл для перебора и отображения полей формы-->
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>  <!-- Вывод текущего поля-->
    <div class="form_error">{{ f.errors }}</div>  <!--Отображение ошибок, связанных с полями-->
    {% endfor %}

    <p><button type="submit">Изменить пароль</button></p>
</form>

{% endblock %}

sitewomen/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->

{% block content %}  <!-- Переопределение блока content -->
<h1>Пароль изменен!</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте новый пароль для
    <a href="{% url 'users:login' %}">входа в систему</a>.</p>

{% endblock %}

sitewomen/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->

{% block content %}  <!-- Переопределение блока content -->
<h1>Новый пароль</h1>

<form method="post">  <!-- Форма для передачи данных методом post -->
    {% csrf_token %}  <!-- Обязательный атрибут csrf -->
    <div class="form-error">{{ form.non_field_errors }}</div>  <!-- Отображение ошибок в заполнении полей формы-->
    {% for f in form %} <!-- Цикл для перебора и отображения полей формы-->
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>  <!-- Вывод текущего поля-->
    <div class="form_error">{{ f.errors }}</div>  <!--Отображение ошибок, связанных с полями-->
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>

</form>

{% endblock %}

sitewomen/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<!-- Инструкция отправляемая на email по сбросу пароля -->
<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

sitewomen/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

sitewomen/users/templates/users/password_reset_form.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->

{% block content %}  <!-- Переопределение блока content -->
<h1>Восстановление пароля</h1>

<form method="post">  <!-- Форма для передачи данных методом post -->
    {% csrf_token %}  <!-- Обязательный атрибут csrf -->
{% for f in form %}  <!-- Цикл для перебора и отображения полей формы-->
<p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>  <!-- Вывод текущего поля-->
<div class="form_error">{{ f.errors }}</div>  <!--Отображение ошибок, связанных с полями-->
{% endfor %}

    <p><button type="submit">Сбросить пароль по E-mail</button></p>
</form>

{% endblock %}

sitewomen/users/templates/users/profile.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->

{% block content %}  <!-- Переопределение блока content -->
<h1>Профиль пользователя</h1>

<form method="post" enctype="multipart/form-data">  <!-- Форма для передачи данных методом post + отображение фото -->
    {% csrf_token %}  <!-- Обязательный атрибут csrf -->
    {% if user.photo %}  <!-- Если photo != 0 (фото присутствует), то отобразить фото по его url -->
    <p><img src="{{ user.photo.url }}"></p>
    {% else %}  <!-- Иначе вывести аватарку по умолчанию -->
    <p><img src="{{ default_image }}"></p>  <!-- Переменная из class ProfileUser -->
    {% endif %}

    <div class="form-error">{{ form.non_field_errors }}</div>  <!-- Отображение ошибок в заполнении полей формы-->
    {% for f in form %} <!-- Цикл для перебора и отображения полей формы-->
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>  <!-- Вывод текущего поля-->
    <div class="form_error">{{ f.errors }}</div>  <!--Отображение ошибок, связанных с полями-->
    {% endfor %}
    <p><button type="submit">Сохранить</button></p>
</form>

<hr>  <!-- Маршрут(Ссылка на класс для смены пароля в профиле пользователя) -->
<p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
{% endblock %}

sitewomen/users/templates/users/register.html
{% extends 'base.html' %}  <!-- Наследование от базового шаблона -->

{% block content %}  <!-- Переопределение блока content -->
<h1>Регистрация пользователя</h1>

<form method="post">  <!-- Форма для передачи данных методом post -->
    {% csrf_token %}  <!-- Обязательный атрибут csrf -->
    <input type="hidden" name="next" value="{{ next }}" />  <!--Скрытая форма для перехода на следующую страницу -->
    <div class="form-error">{{ form.non_field_errors }}</div>  <!-- Отображение ошибок в заполнении полей формы-->
    {% for f in form %} <!-- Цикл для перебора и отображения полей формы-->
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>  <!-- Вывод текущего поля-->
    <div class="form_error">{{ f.errors }}</div>  <!--Отображение ошибок, связанных с полями-->
    {% endfor %}
    <p><button type="submit">Регистрация</button></p>
</form>

{% endblock %}

sitewomen/users/templates/users/register_done.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->

{% block content %}  <!-- Переопределение блока content -->
<h1>Добро пожаловать!</h1>

<p>Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизироваться! Перейдите по этой</p>
<a href="{% url 'users:login' %}">Ссылке</a>
</p>

{% endblock %}