sitewomen/sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include  # импорт include

from sitewomen import settings
from women.views import page_not_found  # импорт page_not_found(после его представления!)
# + папку sitewomen сделали sourse root(рабочий каталог) из-за конфликта в import

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),  # Спец. Функция include позволяет подключить все маршруты автоматически. Если
    # на месте '' прописать свой индекс и еще в файле women/urls.py - то он будет добавляться к адресу автоматически
    path('users/', include('users.urls', namespace="users")),  # путь + связка с приложением users + namespace
    path("__debug__/", include("debug_toolbar.urls")),  # путь для django toolbar
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Связка маршрута MEDIA_URL с
    # общим каталогом sitewomen/media (MEDIA_ROOT) в режиме Debug для корректной работы сервера при обращении в этом
    # режиме и в режиме работы.

handler404 = page_not_found  # обработчик handler404 + ссылка на нашу ф-ию для вывода нашего сообщения при ошибке

admin.site.site_header = "Панель администрирования"  # наш заголовок админки
admin.site.index_title = "Известные женщины мира"  # заголовок ниже уровнем

sitewomen/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy  # импорт функций path
from . import views  # импорт views из текущего модуля

app_name = "users"  # обязательное определение переменной с названием users

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),  # маршрут для авторизации с помощью class LoginUser
    path('logout/', views.logout_user, name='logout'),  # маршрут для выхода с помощью ф-ии logout_user.

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),  # Пользовательский класс для
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),  # смены пароля (template_name=переопределение шаблона со станд-го на пользов-ий)

    path('password-reset/',  # маршруты для стандартных классов сброса пароля
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",  # пользовательский шаблон
             email_template_name="users/password_reset_email.html",  # шаблон, формирующий текст сообщения на email
             success_url=reverse_lazy("users:password_reset_done")), name='password_reset'),  # перенаправление
    path('password-reset/done/',  # сообщение о сбросе пароля
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',  # маршруты для стан-ых классов восстановления пароля
         PasswordResetConfirmView.as_view(  # спец токен (из доку) --> на почту для восстановления пароля
             template_name="users/password_reset_confirm.html",  # пользовательский шаблон
             success_url=reverse_lazy("users:password_reset_complete")),  name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),  # сообщение об успешности восстановления и ссылка на вход



    path('register/', views.RegisterUser.as_view(), name='register'),  # маршрут для класса регистрации пользователя
    path('profile/', views.ProfileUser.as_view(), name='profile'),  # маршрут для класса профиля пользователя
]

sitewomen/women/urls.py
from django.urls import path, register_converter  # импорт функций path, reg_converter из django.urls
from . import views  # импорт views из текущего модуля
from . import converters  # импорт из конверторов(наша папка с созданными конверторами)


register_converter(converters.FourDigitYearConverter, "year4")  # регистрация в Джанго нового конвертера с пом.
# специальной функции register_converter() c именем year4

urlpatterns = [
    path('', views.WomenHome.as_view(), name='home'),  # http://127.0.0.1:8000 - маршр отвеч за гл стр + class WomenHome
    path('about/', views.about, name='about'),  # маршрут about(о сайте)
    path('addpage/', views.AddPage.as_view(), name='addpage'),  # маршр для поля с собств именем class AddPage + as_view
    path('contact/', views.contact, name='contact'),  # маршрут для поля с собственным именем contact
    path('login/', views.login, name='login'),  # маршрут для поля с собственным именем login
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),  # маршрут для шаблона и class ShowPost
    path('category/<slug:cat_slug>/', views.WomenCategory.as_view(), name='category'),  # марш с префиксом для category
    path('tag/<slug:tag_slug>/', views.TagPostList.as_view(), name='tag'),  # маршрут tag/<slug..+ class TagPostList
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),  # маршрут для класса UpdatePage по slug-у
]

sitewomen/women/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


class PublishedManager(models.Manager):  # класс пользовательского менеджера для описания моделей
    def get_queryset(self):  # возвращает опубликованные посты(спец метод базового класса)
        return super().get_queryset().filter(is_published=Women.Status.PUBLISHED)  # возвращает опубликованные статьи


class Women(models.Model):  # наш класс-модель с полями для таблицы
    class Status(models.IntegerChoices):  # класс для именовывания опубликованных/не опубликованных статей в виджете
        DRAFT = 0, 'Черновик'  # название-статус в виджете в виде кортежа с int
        PUBLISHED = 1, 'Опубликовано'  # - костыль в 20 строке - преобразует 1 и 0 в булевы значения

    title = models.CharField(max_length=255, verbose_name="Заголовок")  # Заголовок с максимальным кол-во символов
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="Slug",  # связка с slug в urls
                            validators=[  # стандартные валидаторы для slug + сообщение
                                MinLengthValidator(5, message="Минимум 5 символов"),
                                MaxLengthValidator(100, message="Максимум 100 символов")])

    photo = models.ImageField(upload_to="photos/%y/%m/%d", default=None,  # поле для загрузки фото для постов +
                              blank=True, null=True, verbose_name="Фото")  # параметры загрузки(каталог, имя...)
    content = models.TextField(blank=True, verbose_name="Текст статьи")  # Поле для текста(статьи) с доступно пустым
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")  # авто заполнение времени
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")  # меняющееся при каждом изменении
    is_published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),  # Публикация +
                                       default=Status.DRAFT, verbose_name="Статус")  # костыль "опубликовано" в админке

    cat = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='posts', verbose_name="Категории")
    # вторичной модели(women) к первичной (category) через ForeignKey + 'Category'(т.к. задан раньше) +
    # on_delete=..PROTECT(запрет на удаление постов) + related_name с собственным названием для привязки к вторич модели
    tags = models.ManyToManyField('TagPost', blank=True, related_name='tags', verbose_name="Теги")  # many-to-many
    husband = models.OneToOneField('Husband', on_delete=models.SET_NULL,  # вывести Null в поле, где были удалены данные
                                   null=True, blank=True, related_name='wuman', verbose_name="Муж")
    # Параметр husband для связи one-to-one модели Women со своими свойствами(пустые поля, значения null и т. д.) +
    # ко всем полям добавлен verbose_name для отображения в админ панели.
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL,  # атрибут связывает конкретную статью с её
                               related_name='posts', null=True, default=None)  # Автором. Получение модели get_user_mo-l
    # Связь ForeignKey(многие к одному) + доп параметры персонального имени, обратного связывания.

    objects = models.Manager()  # пользовательский менеджер по умолчанию (работает, если published не активен)
    published = PublishedManager()  # пользовательский менеджер публикаций(да/нет)

    def __str__(self):  # ф-я возвращает главное поле при запросах
        return self.title

    class Meta:  # спец класс для сортировки полей модели Women с методом ordering и indexes + порядок сортировки
        verbose_name = "Известные женщины"  # заголовок для админки
        verbose_name_plural = "Известные женщины"  # заголовок во множественном числе (без -s)
        ordering = ['-time_create']  # порядок сортировки
        indexes = [  # список индексированных полей для ускорения сортировки
            models.Index(fields=['-time_create'])  # class Meta - для управления сортировкой на уровне класса
        ]

    def get_absolute_url(self):  # метод, формирующий url для каждой конкретной записи
        return reverse('post', kwargs={'post_slug': self.slug})  # ф-я reverse возвращает полноценный url адрес


class Category(models.Model):  # Модель Category в виде класса для связи many-to-one (нашей первичной модели category)
    name = models.CharField(max_length=100, db_index=True, verbose_name="Категория")  # имя категории + индекс-е поле
    slug = models.SlugField(max_length=255, unique=True, db_index=True)  # поле для обращения по slug + index

    class Meta:  # мета класс для вывода класса Category в админ панель
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):  # метод вывода информации
        return self.name

    def get_absolute_url(self):  # метод для формирования URl адреса (см шаблон в list_categories.html)
        return reverse('category', kwargs={'cat_slug': self.slug})  # возвращает с помощью reverse маршрут по
# имени Category и выводить из таблицы по полю slug


class TagPost(models.Model):  # модель для тегов наследуем от класса Model
    tag = models.CharField(max_length=100, db_index=True)  # название тега(индексированное) + max длина 100 символов
    slug = models.SlugField(max_length=255, unique=True, db_index=True)  # поле для slug (уникален и индексирован)

    def __str__(self):  # метод для отображения названия тегов
        return self.tag

    def get_absolute_url(self):  # метод возвращает url для конкретного тега(также отвечает в админке-смотреть на сайте)
        return reverse('tag', kwargs={'tag_slug': self.slug})  # slug берется из бд и формируется маршрут


class Husband(models.Model):  # модель поля Husband с параметрами длины и типа водимых данных
    name = models.CharField(max_length=100)  # поля для Husband...
    age = models.IntegerField(null=True)
    m_count = models.IntegerField(blank=True, default=0)

    def __str__(self):  # возвращает имя для наглядности
        return self.name


class UploadFiles(models.Model):  # класс для загрузки файлов с использованием модели
    file = models.FileField(upload_to='uploads_model')  # переменная с параметром(путь для загрузки файлов)

sitewomen/women/forms.py
from django import forms  # forms дает классы для формы
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.utils.deconstruct import deconstructible

from .models import Category, Husband, Women


@deconstructible  # (вариант валидатора 1 на уровне класса + декоратор) декоратор для создания валидатора
class RussianValidator:  # класс пользовательского валид-ра(удобен для частого общего использования) без базового класса
    AllOWED_CHARS = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя0123456789- "  # допустимые сим-ы
    code = 'russian'  # пользовательское название валидатора

    def __init__(self, message=None):  # инициализатор с одним параметром message=None
        self.message = message if message else "Должны присутствовать только русские символы, цифры, дефис, пробел."
        # атрибут с проверкой (Если передаем сообщение об ошибки - оно используется, если нет - выводится блок else)

    def __call__(self, value, *args, **kwargs):  # call вызывает проверку на корректность, если валидатор срабатывает
        if not (set(value) <= set(self.AllOWED_CHARS)):  # проверка на корректность вводимых символов из ALLOWED_CHARS
            raise ValidationError(self.message, code=self.code)  # исключение с сообщением об ошибке + передача code


"""" Формы связанные с моделями упрощают работу в целом, имеют встроенные методы из Джанго, более удобны. Пример ниже.
Это класс наследуемый от ModelForm, имеющий class Meta, свои валидаторы + form.save() """


class AddPostForm(forms.ModelForm):  # класс связан с моделью (служит для автоматизации полей формы)
    cat = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Категория не выбрана", label="Категория")
    # Отображение поля в виде выпадающего списка
    husband = forms.ModelChoiceField(queryset=Husband.objects.all(), required=False, empty_label="Не замужем",
                                     label="Муж")  # empty_label - отображение надписи в пустом поле

    class Meta:  # вложенный класс Мета для привязки формы AddPostForm с моделью Women + имеет метод save()
        model = Women  # описывает связь формы с моделью Women
        fields = ['title', 'slug', 'content', 'photo', 'is_published', 'cat', 'husband', 'tags']  # все поля берутся из
        # Women и указываются только те поля, которые есть в Women. Желательно прописывать конкретно отображаемые поля.
        widgets = {  # виджеты для поля заголовок и текст статьи
            'title': forms.TextInput(attrs={'class': 'form-input'}),  # поле, вид заполнения, стиль оформл-ия form-input
            'content': forms.Textarea(attrs={'cols': 50, 'rows': 5}),  # поле, вид заполнителя, 50 символов, 5 рядов
        }
        labels = {'slug': 'URL'}  # поле Slug отображается с названием URL

    def clean_title(self):  # Наш валидатор для проверки на корректность вводимых данных (не более 50 символов)
        title = self.cleaned_data['title']  # title получить из clean_data
        if len(title) > 50:
            raise ValidationError("Длина превышает 50 символов")

        return title

    # """ Вариант валидатора 2 на уровне метода - проще первого, подходит лучше для частной проверки"""
    # def clean_title(self):  # спец метод clean_имя поля для проверки (title в данном случае)
    #     title = self.cleaned_data['title']  # из словаря cleaned_data получаем значение по ключу title, далее проверка
    #     AllOWED_CHARS = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя0123456789- "
    #
    #     if not (set(title) <= set(AllOWED_CHARS)):  # проверка на корректность вводимых символов из ALLOWED_CHARS
    #         raise ValidationError("Должны присутствовать только русские символы, цифры, дефис, пробел.")  # исключение


class UploadFileForm(forms.Form):  # класс не привязан к модели и формируется на базе Form(позволяет загружать файл)
    file = forms.ImageField(label='Файл')  # переменная file + тип поля(для img) + именная метка

sitewomen/women/templates/women/about.html
{% extends 'base.html' %} <!-- тэг extends + путь к базовому файлу-шаблонов base-->

{% block content %} <!-- Блок наследуется из базового файла-шаблонов base-->
<h1>{{ title }}</h1> <!-- Наша переменная, содержащаяся в ф-ии представления about-->
{% for item in page_obj %}  <!-- Перебор элементов страницы через page_obj с помощью for -->
<p>{{ item.pk }}: {{ item.title }}</p>  <!-- item(объект класса Women) Вывод итерируемого элемента + pk -->
{% endfor %}

<nav>
    <ul> <!-- Маркерованный список-->
        {% for p in page_obj.paginator.page_range %} <!-- Ите-р page_range обращ-я к объекту paginator через page_obj-->
        <li>
            <a href="?page={{ p }}">{{ p }}</a> <!-- Формирование ссылки - к запросу page + номер страницы и отображ-е -->
        </li>
        {% endfor %}
    </ul>
</nav>
{% endblock %}

sitewomen/women/templates/women/addpage.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>
<form action="" method="post" enctype="multipart/form-data">  <!-- Формы для полей на странице добавления статей, -->
    <!-- "" - отрабатывает на текущей странице + обязательный параметр enctype="multipart/form-data" -->
    {% csrf_token %} <!-- CSRF - для защиты вводимых данных по требованию безопасности -->
    <div class="form-error">{{ form.non_field_errors }}</div>  <!-- Отображение ошибок в заполнении полей формы-->
    {% for f in form %} <!-- Цикл для перебора полей формы-->
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>  <!-- Вывод текущего поля-->
    <div class="form_error">{{ f.errors }}</div>  <!--Отображение ошибок-->
    {% endfor %}
    <p><button type="submit">Отправить</button> </p>
</form>
{% endblock %}

sitewomen/women/templates/women/index.html
{% extends 'base.html' %}  <!-- index.html - шаблон отображающий главную страницу -->

{% block content %}
<ul class="list-articles">
	{% for p in posts %} <!-- примеры for и if-->
			<li><div class="article-panel"> <!-- Оформление с помощью div -->
	<p class="first">Категория: {{p.cat.name}} | автор: <!-- Обращение к p.cat и отобразить название категории через models.py-->
	{{ p.author.username|default:"Автор неизвестен" }}</p>	<!--Вывод автора статьи в заголовке, либо текст -->
	<p class="last">Дата: {{p.time_update|date:"d-m-Y H:i:s"}}</p> <!-- Отображение даты и времени-->
	</div>
{% if p.photo %} <!-- Если фото ссылается на существующее изображение - отобразить мини-фото по указанному адресу -->
        <p><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
{% endif %}
				<h2>{{p.title}}</h2>
    {% autoescape off %} <!-- Тэг управляющий за автоматическое экранирование внутри блока -->
	{{p.content|linebreaks|truncatewords:40}} <!-- linebreaks - фильтр переноса на след строку и ограничитель символов-->
    {% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p> <!-- Реализация ссылки post-->
			</li> <!-- класс + ссылка на post(кнопка читать статью) + ссылка на метод get_absolut_url -->
	{% endfor %}
</ul>
{% endblock %}


{% block navigation %}  <!-- Переопределение блока навигации из базового шаблона-->
{% if page_obj.has_other_pages %}  <!-- Проверка на наличие следующей страницы(убрать навигацию, если страница одна -->
<nav class="list-pages">  <!-- Стиль страницы (передаются в ccs файле) -->
	<ul>
		{% if page_obj.has_previous %}  <!-- Проверка на существование предыдущей страницы -->
		<li class="page-num">  <!-- Стиль кнопки перехода на предыдущую страницу -->
			<a href="?page={{ page_obj.previous_page_number }}">&lt;</a>  <!-- Ссылка + номер предыдущей страницы -->
		</li>
		{% endif %}

		{% for p in paginator.page_range %} <!-- Цикл перебирает в пагинаторе итерированные объекты(номер страницы) -->
		{% if page_obj.number == p %}  <!-- Если текущая страница == p, то номер страницы отображать в виде текста -->
		<li class="page-num page-num-selected">{{ p }}</li>  <!-- Стиль отображения текста номера страницы -->
		{% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}  <!-- Диапазон отображения страниц от текущей
		страницы две влево и две вправо (|add:2 или |add:-2 позволяет +2 и -2 от текущего номера страницы -->
		<li class="page-num">  <!-- Стиль нумерации страниц -->
			<a href="?page={{ p }}">{{ p }}</a>  <!-- Формирование ссылок - к запросу page + номер стр-ы и отображение-->
		</li>
		{% endif %}
		{% endfor %}

		{% if page_obj.has_next %} <!-- Проверка на наличие следующей страницы -->
		<li class="page-num">  <!-- Стиль кнопки перехода на следующую страницу -->
			<a href="?page={{ page_obj.next_page_number }}">&gt;</a>  <!-- Ссылка + номер следующей страницы -->
		</li>
		{% endif %}
	</ul>
</nav>
{% endif %}
{% endblock %}

sitewomen/women/templates/women/list_categories.html
{% for cat in cats %} <!-- Цикл с перебором переменной cats из women_tags(def show_categories)-->
{% if cat_id == cat_selected %} <!-- Проверка на соответствие-->
<li class="selected">{{cat.name}}</li> <!-- Если проверка проходит, то вступает оформление со стилем selected-->
{% else %}
<li><a href="{{ cat.get_absolute_url }}">{{cat.name}}</a></li> <!-- get_absolute_url формирует url адрес + ключ name-->
{% endif %}
{% endfor %}

sitewomen/women/templates/women/list_tags.html
{% if tags %} <!-- Шаблон для проверки на наличие тегов и формирование список из ссылок на тот или иной тег-->
    <p>Теги:</p>
    <ul class="tags-list">
        {% for t in tags %} <!-- Перебрать все теги из TagPost-->
        <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li> <!-- Сформиров list из ссылок, отображая адрес и название-->
        {% endfor %}
    </ul>
{% endif %}

sitewomen/women/templates/women/post.html
{% extends 'base.html' %} <!-- Шаблон для отображения статьи-->

{% block breadcrumbs %} <!-- блок из base.html-->
{% if perms.women.change_women %}  <!-- Обращение через perms к пользователям - Если у них есть права на редактирование-->
<p><a href="{% url 'edit_page' post.slug %}">Редактировать статью</a></p>  <!-- Тогда вывод ссылки на редактирование статьи-->
{% endif %}

<!-- Теги -->
{% with post.tags.all as tags %} <!-- post(текущ отображаемая запись из Women) выбир все теги через ОРМ и переноc в tags-->
{% if tags %} <!-- проверка на наличие -->
<ul class="tags-list">
    <li>Теги:</li>
    {% for t in tags %} <!-- Перебор через цикл всех прочитанных тегов и отобразить в виде ссылок-->
    <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}
{% endblock %}

{% block content %}
<h1>{{post.title}}</h1>

{% if post.photo %}
<p><img class="img-article-left" src="{{post.photo.url}}"></p>
{% endif %}

{{post.content|linebreaks}}
{% endblock %}