sitewomen/sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include  # импорт include

from sitewomen import settings
from women.views import page_not_found  # импорт page_not_found(после его представления!)
# + папку sitewomen сделали sourse root(рабочий каталог) из-за конфликта в import

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),  # Спец. Функция include позволяет подключить все маршруты автоматически. Если
    # на месте '' прописать свой индекс и еще в файле women/urls.py - то он будет добавляться к адресу автоматически
    path('users/', include('users.urls', namespace="users")),  # путь + связка с приложением users + namespace
    path("__debug__/", include("debug_toolbar.urls")),  # путь для django toolbar
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Связка маршрута MEDIA_URL с
    # общим каталогом sitewomen/media (MEDIA_ROOT) в режиме Debug для корректной работы сервера при обращении в этом
    # режиме и в режиме работы.

handler404 = page_not_found  # обработчик handler404 + ссылка на нашу ф-ию для вывода нашего сообщения при ошибке

admin.site.site_header = "Панель администрирования"  # наш заголовок админки
admin.site.index_title = "Известные женщины мира"  # заголовок ниже уровнем

sitewomen/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy  # импорт функций path
from . import views  # импорт views из текущего модуля

app_name = "users"  # обязательное определение переменной с названием users

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),  # маршрут для авторизации с помощью class LoginUser
    path('logout/', views.logout_user, name='logout'),  # маршрут для выхода с помощью ф-ии logout_user.

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),  # Пользовательский класс для
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),  # смены пароля (template_name=переопределение шаблона со станд-го на пользов-ий)

    path('password-reset/',  # маршруты для стандартных классов сброса пароля
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",  # пользовательский шаблон
             email_template_name="users/password_reset_email.html",  # шаблон, формирующий текст сообщения на email
             success_url=reverse_lazy("users:password_reset_done")), name='password_reset'),  # перенаправление
    path('password-reset/done/',  # сообщение о сбросе пароля
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',  # маршруты для стан-ых классов восстановления пароля
         PasswordResetConfirmView.as_view(  # спец токен (из доку) --> на почту для восстановления пароля
             template_name="users/password_reset_confirm.html",  # пользовательский шаблон
             success_url=reverse_lazy("users:password_reset_complete")),  name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),  # сообщение об успешности восстановления и ссылка на вход



    path('register/', views.RegisterUser.as_view(), name='register'),  # маршрут для класса регистрации пользователя
    path('profile/', views.ProfileUser.as_view(), name='profile'),  # маршрут для класса профиля пользователя
]

sitewomen/templates/base.html
{% load static %}
{% load women_tags %}

<! DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'women/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'women/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %} <!--Блок с названием mainmenu-->
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
{% for m in mainmenu %}  <!-- Главное меню передается из шаблона конт-го проц-ра get_women_context -->
	<li><a href="{% url m.url_name %}">{{m.title}}</a></li> <!--Пример оформления в столбец с помощью цикла выше-->
{% endfor %}
{% if user.is_authenticated %}  <!--Если пользователь авторизован(обращение к user, благодаря context_processor.auth)-->
	<li	class="last"><a href="{% url 'users:profile' %}"> {{user.username}}</a> | <a href="{% url 'users:logout' %}">Выйти</a></li>  <!--Логика выхода и ниже-->
{% else %}  <!--Last + username(доступно и связано с именем пользователя в БД) + ссылка маршрута для выхода из сис-мы + ссылка на профиль пользователя -->
	<li class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}">Регистрация</a></li>  <!--Логика ниже-->
{% endif %}	<!--last(пункт меню в конце панели) + маршрут + кнопки: войти и ссылка на функции для регистрации -->
			</ul>  <!--Куда перенаправлять (users:login, где users - пространство имен для всех url приложения users)-->
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		{% if cat_selected == 0 %} <!--условие для проверки на выделение в категориях-->
		<li class="selected">Все категории</li>
		{% else %}
		<li><a href="{% url 'home' %}">Все категории</a></li> <!--ссылка на домашнюю страницу по else-->
		{% endif %}

		{% show_categories cat_selected %} <!--реализация с помощью inclusion_tag() из list_categories-->

		<li class="share">
		<p>Наш канал</p>
		<a class="share-yt" href="https://www.youtube.com/" target="_blank" rel="nofollow"></a>
		</li>

		<li>{% show_all_tags %}</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

<!-- Блок навигации -->
{% block navigation %}
{% endblock %}
<!-- Конец блока навигации -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2024 Частичное или полное копирование информации с данного сайта строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>